name: debugger-action
#on: 
#  watch:
#    types: started
on: [push1]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
 
     - name: Setup Debug Session
       uses: csexton/debugger-action@master
